version: '3.8'

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.21
    ports:
      - 80:80 # когда мы будем обращаться к порту 80 на компьютере, мы будем перенаправлены на порт 80 контейнера Nginx.
    volumes: # файлы, которые хотим подключить к контейнеру
      - ./app:/var/www/php
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./
    working_dir: /var/www/php
    volumes:
      - ./app:/var/www/php
    depends_on:
      mysql: # сначала должен быть запущен новый MySQL сервер
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%' # разрешить подключения с любого IP-адреса 
      MYSQL_DATABASE: demo
    command: --init-file /data/application/init.sql
    volumes:
      - ./conf.d/my.cnf:/etc/mysql/conf.d/my.cnf # файл конфигурации
      - mysqldata:/var/lib/mysql # том, чтобы сделать базу данных постоянной
      - ./sql/dilemma.sql:/data/application/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

# Volumes
volumes:
  mysqldata: